-- =========================================================
-- School EMIS — Full Supabase Schema (fixed)
-- Safe to re-run: uses IF NOT EXISTS everywhere, and patches
-- any pre-existing tables that are missing expected columns.
-- =========================================================

-- ---------------------------------------------------------
-- Students
-- ---------------------------------------------------------
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  admission_no text unique not null,
  full_name text not null,
  class_name text not null,
  guardian_name text,
  phone text,
  email text
);

-- ---------------------------------------------------------
-- Attendance
-- ---------------------------------------------------------
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('Present', 'Absent', 'Late'))
);

-- ---------------------------------------------------------
-- Fee Records
-- ---------------------------------------------------------
create table if not exists public.fee_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  amount numeric(10,2) not null,
  payment_date date not null,
  status text not null check (status in ('Paid', 'Pending', 'Overdue')),
  payment_method text not null default 'Cash',
  note text
);

alter table public.fee_records
  add column if not exists payment_method text not null default 'Cash';

alter table public.fee_records
  add column if not exists note text;

-- ---------------------------------------------------------
-- Teachers
-- ---------------------------------------------------------
create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  subject text,
  phone text,
  email text,
  salary numeric(10,2) not null default 0.00
);

alter table public.teachers
  add column if not exists salary numeric(10,2) not null default 0.00;

-- ---------------------------------------------------------
-- Teacher Salary Payments
-- ---------------------------------------------------------
create table if not exists public.teacher_salary_payments (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  teacher_id bigint references public.teachers(id) on delete cascade,
  amount numeric(10,2) not null default 0,
  allowance numeric(10,2) not null default 0,
  deduction numeric(10,2) not null default 0,
  bonus numeric(10,2) not null default 0,
  net_amount numeric(10,2) not null default 0,
  payment_method text not null default 'Cash',
  payment_date date,
  payment_month text,
  note text
);

-- Patch in case an older/partial version of this table exists without these columns
alter table public.teacher_salary_payments add column if not exists amount numeric(10,2) not null default 0;
alter table public.teacher_salary_payments add column if not exists allowance numeric(10,2) not null default 0;
alter table public.teacher_salary_payments add column if not exists deduction numeric(10,2) not null default 0;
alter table public.teacher_salary_payments add column if not exists bonus numeric(10,2) not null default 0;
alter table public.teacher_salary_payments add column if not exists net_amount numeric(10,2) not null default 0;
alter table public.teacher_salary_payments add column if not exists payment_method text not null default 'Cash';
alter table public.teacher_salary_payments add column if not exists payment_date date;
alter table public.teacher_salary_payments add column if not exists payment_month text;
alter table public.teacher_salary_payments add column if not exists note text;

-- ---------------------------------------------------------
-- Courses
-- ---------------------------------------------------------
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  course_name text not null,
  class_name text not null,
  teacher_name text
);

-- ---------------------------------------------------------
-- Marks
-- ---------------------------------------------------------
create table if not exists public.marks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  subject text not null,
  score integer not null,
  term text not null
);

-- ---------------------------------------------------------
-- Library Books
-- ---------------------------------------------------------
create table if not exists public.library_books (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  author text,
  isbn text,
  total_copies integer not null check (total_copies >= 0),
  available_copies integer not null check (available_copies >= 0)
);

-- ---------------------------------------------------------
-- Library Loans
-- ---------------------------------------------------------
create table if not exists public.library_loans (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  book_id bigint references public.library_books(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  issue_date date not null,
  due_date date not null,
  return_date date,
  status text not null check (status in ('Issued', 'Returned', 'Overdue')),
  fine_amount numeric(10,2) not null default 0
);

-- ---------------------------------------------------------
-- Student Signup
-- ---------------------------------------------------------
create table if not exists public.student_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null default '',
  admission_no text not null default '',
  class_name text not null default '',
  guardian_name text not null default '',
  phone text not null default '',
  email text not null default '',
  username text unique not null,
  password text not null,
  role text not null default 'student',
  student_id bigint
);

-- ---------------------------------------------------------
-- Admin Signup
-- ---------------------------------------------------------
create table if not exists public.admin_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'admin',
  admin_id bigint
);

-- Patch: if admin_signup already existed from an earlier/partial run,
-- make sure it has the columns this script (and the app) expects.
alter table public.admin_signup add column if not exists full_name text;
alter table public.admin_signup add column if not exists phone text;
alter table public.admin_signup add column if not exists email text;
alter table public.admin_signup add column if not exists role text not null default 'admin';
alter table public.admin_signup add column if not exists admin_id bigint;

-- Move any older admin account out of the student account table.
insert into public.admin_signup (full_name, phone, email, username, password, role)
select full_name, phone, email, username, password, 'admin'
from public.student_signup
where role = 'admin'
on conflict (username) do nothing;

delete from public.student_signup where role = 'admin';

-- ---------------------------------------------------------
-- Teacher Signup
-- ---------------------------------------------------------
create table if not exists public.teacher_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  subject text,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'teacher',
  teacher_id bigint
);
alter table public.teacher_signup add column if not exists subject text;
alter table public.teacher_signup add column if not exists phone text;
alter table public.teacher_signup add column if not exists email text;

-- ---------------------------------------------------------
-- Principal Signup
-- ---------------------------------------------------------
create table if not exists public.principal_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'principal',
  principal_id bigint
);
alter table public.principal_signup add column if not exists phone text;
alter table public.principal_signup add column if not exists email text;

-- ---------------------------------------------------------
-- Accountant Signup
-- ---------------------------------------------------------
create table if not exists public.accountant_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'accountant',
  accountant_id bigint
);
alter table public.accountant_signup add column if not exists phone text;
alter table public.accountant_signup add column if not exists email text;

-- ---------------------------------------------------------
-- Librarian Signup
-- ---------------------------------------------------------
create table if not exists public.librarian_signup (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  full_name text not null,
  phone text,
  email text,
  username text unique not null,
  password text not null,
  role text not null default 'librarian',
  librarian_id bigint
);
alter table public.librarian_signup add column if not exists phone text;
alter table public.librarian_signup add column if not exists email text;

-- ---------------------------------------------------------
-- Ratings (used by the student "Rate Your Experience" widget)
-- ---------------------------------------------------------
-- ---------------------------------------------------------
-- Ratings
-- ---------------------------------------------------------
create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  student_id bigint references public.students(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text
);

-- ---------------------------------------------------------
-- Row Level Security
-- For quick local/dev testing, RLS is disabled below so the
-- anon/service key your app uses can read and write freely.
-- Re-enable and add proper policies before going to production.
-- ---------------------------------------------------------
alter table public.students disable row level security;
alter table public.attendance disable row level security;
alter table public.fee_records disable row level security;
alter table public.teachers disable row level security;
alter table public.teacher_salary_payments disable row level security;
alter table public.courses disable row level security;
alter table public.marks disable row level security;
alter table public.library_books disable row level security;
alter table public.library_loans disable row level security;
alter table public.student_signup disable row level security;
alter table public.admin_signup disable row level security;
alter table public.teacher_signup disable row level security;
alter table public.principal_signup disable row level security;
alter table public.accountant_signup disable row level security;
alter table public.librarian_signup disable row level security;
alter table public.ratings disable row level security;

-- ---------------------------------------------------------
-- Reload PostgREST's schema cache so the API sees these
-- tables/columns immediately instead of waiting for auto-refresh.
-- ---------------------------------------------------------
notify pgrst, 'reload schema';